AppBundle\Entity\Contenir:
    repositoryClass: AppBundle\Repository\ContenirRepository
    type: entity
    table: contenir
    fields:
        quantite_produit:
            type: integer
        date_panier:
            type: datetime
    id:
        manyToOne:
            id_panier:
                targetEntity: Panier
                joinColumns:
                    panier:
                        referencedColumnName: id_panier
        manyToOne:
            ref_produit:
                targetEntity: Produit
                joinColumns:
                    produit:
                        referencedColumnName: ref_produit
