AppBundle\Entity\Olol:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\OlolRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: '20'
        visible:
            type: boolean
    lifecycleCallbacks: {  }
